Update ytmp

diff --git a/ytmp b/ytmp
--- a/ytmp
+++ b/ytmp
@@ -1,6 +1,6 @@
 #!/bin/sh
 # YTMP: a shell script for searching, playing, downloading, and keeping track of music from youtube and local files with extensive queue management using fzf, vim, or cli
-# DEPS: yt-dlp, mpv, socat, fzf, xargs, find, sed, bc, ed, coreutils, (pipe-viewer for playlist search), (notify-send for notifcations), (curl for thumbnails), (n/vim)
+# DEPS: yt-dlp, mpv, socat, fzf, xargs, find, sed, bc, ed, coreutils, (pipe-viewer for playlist search), (notify-send for notifications), (curl for thumbnails), (n/vim)
 # set -xv
 
 [ -z "$prefix" ] && prefix="/home/$USER/Music/ytmp"
@@ -221,18 +221,6 @@ CAT_EOF
 exit
 }
 
-notify () {
-	case "$1" in
-		both) shift 1; echo "$@"; [ "$notifications" = '1' ] && notify-send "$@" ;;
-		term) shift 1; echo "$@" ;;
-		ifnoterm) echo "$-"; shift 1; if ! echo "$-" | grep -q 'i'; then
-					[ "$notifications" = '1' ] && notify-send "$@"
-					else echo "$@"; fi
-			;;
-	esac
-	return 0
-}
-
 # adds entries to queue while scanning to see if entry is already in the queue;
 # if it is, doesn't add to the queue but notes where the id is found in the queue,
 # the length of the queue, <id>, <title> in /tmp/ytmpqdiscards so the user can be given a choice
@@ -328,7 +316,7 @@ register () {
 # add urls, playlists, dirs, paths
 add () {
 	shift 1
-	[ -z "$1" ] && echo "Provide a url, path, or directory to add as arguement" && return
+	[ -z "$1" ] && echo 'Provide a url, path, or directory to add as arguement' && return
 
 	rm -f "$qdiscards_file"
 	for f in "$@"; do
@@ -409,7 +397,7 @@ search_youtube () {
 }
 
 search_playlist () {
-	[ -z "$2" ] && notify ifnoterm 'Provide a search string as arguement.' && return
+	[ -z "$2" ] && echo 'Provide a search string as arguement.' && return
 	query=$( echo "$*" | cut -d' ' -f2- )
 	playlist_sel="$( pipe-viewer --no-use-colors --no-interactive --results=50 -sp --custom-playlist-layout='*URL* *TITLE*' "$query" | sed -n -e 1d -e "\@https://www.youtube.com/playlist?list=@p" | tee /tmp/ytmpplaylists | cut -d" " -f2- | grep -n '' | fzf --prompt='search: ' --info=inline --padding=2,2,2,2 --border=bottom --color=hl+:bold:bright-red,hl:bright-red,label:italic:white,marker:cyan,pointer:cyan,bg+:black,label:white,info:white:dim,label:white:dim,spinner:white:dim --border-label-pos=3 --border-label="{   ytmp playlist select   }" --separator='' \
 	--layout=reverse --height 60% -m --bind='ctrl-j:jump,home:first,end:last,ctrl-k:kill-line,shift-tab:clear-selection,tab:toggle+down,ctrl-x:execute(echo {n}+1 | bc | xargs -I ,, ytmp spr p ,,)' --preview='echo {n}+1 | bc | xargs -I ",," sed -n ,,p /tmp/ytmpplaylists | xargs -0 -I ",," pipe-viewer --no-use-colors --results=50 --custom-layout="*AUTHOR* *TIME* *TITLE*" --no-interactive ",," | sed 1d' | grep '^[0-9]*:' )"
@@ -441,7 +429,7 @@ upd_amnt_played () {
 			echo "$id $amnt_played $dt dl $title" >> $played_urls
 		else
 			len=$( yt-dlp -q --no-warnings --get-duration "https://www.youtube.com/watch?v=$id" | sed -E 's/(.*):(.+):(.+)/\1*3600+\2*60+\3/;s/(.+):(.+)/\1*60+\2/' | bc )
-			[ $len -lt $max_len_for_dl ] && ( notify both "Downloading '${title}.' You have listened to it $amnt_played times. Playback will start once download finishes." && yt-dlp -q --no-warnings -f bestaudio -o "$songs_dir/%(id)s %(title)s.%(ext)s" "https://www.youtube.com/watch?v=$id" >/dev/null 2>&1 && echo "$id $amnt_played $dt dl $title" >> $played_urls ) || echo "$id $amnt_played $dt $title" >> $played_urls
+			[ $len -lt $max_len_for_dl ] && ( echo "Downloading '${title}.' You have listened to it $amnt_played times. Playback will start once download finishes." && yt-dlp -q --no-warnings -f bestaudio -o "$songs_dir/%(id)s %(title)s.%(ext)s" "https://www.youtube.com/watch?v=$id" >/dev/null 2>&1 && echo "$id $amnt_played $dt dl $title" >> $played_urls ) || echo "$id $amnt_played $dt $title" >> $played_urls
 		fi
 	else
 		ls $songs_dir/*"${id}"* >/dev/null 2>&1 && echo "$id $amnt_played $dt dl $title" >> $played_urls || echo "$id $amnt_played $dt $title" >> $played_urls
@@ -482,7 +470,8 @@ play () {
 		dl_thumbnail
 	fi
 	title="$( sed -n -e "/$playing_regex/s/$playing_marker_regex//" -e 's/\*\*\*$//p' "$queue" )"
-	notify both 'Now Playing' "'$title'"
+	echo 'Now Playing' "'$title'"
+	[ "$notifications" = 1 ] && notify-send 'Now Playing' "'$title'"
 	sh "$run_on_next" >/dev/null 2>&1 &
 	[ "$daemonize" = 1 ] && ! pgrep -fa 'ytmp -d' && setsid -f ytmp -d >/dev/null 2>&1
 }
@@ -603,9 +592,9 @@ queue_manager () {
 fuzzy_play () {
 	shift 1
 	query="$@"
-	[ -z "$query" ] && echo "Provide a string to search as argument." && return
+	[ -z "$query" ] && echo 'Provide a string to search as argument.' && return
 	match=$( grep -n '' "$queue" | sed -E -e 's/\(?[0-9]*[Rr]emaster(ed)? ?\)? ?[0-9]*//g' -e 's/( - )?(  )?(\)$)?( $)?//g' | fzf --tiebreak=chunk,begin -f "$query" | head -1 | cut -d':' -f1 )
-	[ -n "$match" ] && playlist e a "$match" || echo 'Match not found.'
+	if [ -n "$match" ]; then playlist e a "$match"; else echo 'Match not found.'; fi
 	return
 }
 
@@ -632,7 +621,7 @@ rand_daemon () {
 }
 
 fzf_preview () {
-	[ -z "$3" ] && echo 'Provide a line number' && return
+	[ -z "$3" ] && echo 'Provide a line number.' && return
 	fzf_index="$( echo "$3" | sed -e s/m/"$( cat /tmp/ytmpmark )"/ -e s/p/"$( grep -n "$playing_regex" "$queue" | head -1 | cut -d':' -f1 )"/ -e s/l/"$( grep -c '.' "$queue" )"/ | bc )"
 
  	[ "$2" = s ] && id="$( sed -n ${fzf_index}p /tmp/ytmpids | cut -d" " -f1 )" || id="$( sed -n "${fzf_index}s/${field_regex}/\1/p" "$queue" )"
@@ -714,7 +703,7 @@ case "${1}" in
 	-dl) download_song $* ;;
 	-d) playlist "$@" ;;
 	-r) rand_daemon $* ;;
-	-n) while true; do ( ! echo '{ "command": ["get_property", "pid"] }' | socat - /tmp/mpvsocketytmp >/dev/null 2>&1 ) && sleep .5 && return 0; done ;;
+	-n) while true; do ( ! pgrep -fa 'mpv.*--input-ipc-server=/tmp/mpvsocketytmp' >/dev/null 2>&1 ) && sleep .5 && return 0; done ;;
 	-l) echo '{ "command": ["set_property", "loop", true] }' | socat - /tmp/mpvsocketytmp >/dev/null 2>&1 ;;
 	-qa) echo quit | socat - /tmp/mpvsocketytmp ;;
 	-kd) pkill -f 'ytmp -d'; exit ;;
